name: GeneralFeatures
version: '1.0-SNAPSHOT'
main: saturn.generalFeatures.GeneralFeatures
api-version: '1.21'
load: STARTUP
authors: [ ___Pumpkinn ]

commands:
  grace:
    description: Control PvP protection grace period
    usage: /grace <enable|disable|status> [time]
    aliases: [graceperiod]
    permission: generalfeatures.grace
    permission-message: You don't have permission to use this command

  nether:
    description: Control access to the Nether dimension
    usage: /nether <enable|disable|status> [time]
    permission: generalfeatures.nether
    permission-message: You don't have permission to use this command

  end:
    description: Control access to the End dimension
    usage: /end <enable|disable|status> [time]
    permission: generalfeatures.endcontrol
    permission-message: You don't have permission to use this command

  restrictions:
    description: Manage item restrictions (pearls, fireworks, potions)
    usage: /restrictions <enable|disable|potion|list> [options]
    permission: generalfeatures.restrictions
    permission-message: You don't have permission to use this command

  teleportend:
    description: Teleport to the End dimension
    usage: /teleportend
    aliases: [tpend]
    permission: generalfeatures.teleportend
    permission-message: You don't have permission to use this command

  broadcast:
    description: Send customizable broadcasts to all players
    usage: /broadcast [options] <message>
    aliases: [bc, announce]
    permission: generalfeatures.broadcast
    permission-message: You don't have permission to use this command

permissions:
  generalfeatures.grace:
    description: Allows controlling PvP grace period
    default: op

  generalfeatures.nether:
    description: Allows controlling access to the Nether
    default: op

  generalfeatures.endcontrol:
    description: Allows controlling access to the End dimension
    default: op

  generalfeatures.endcontrol.notify:
    description: Receive notifications about End dimension status changes
    default: op

  generalfeatures.restrictions:
    description: Allows managing game restrictions
    default: op

  generalfeatures.teleportend:
    description: Allows teleporting to the End dimension
    default: op

  generalfeatures.broadcast:
    description: Allows sending broadcasts
    default: op