name: GeneralFeatures
version: '1.0-SNAPSHOT'
main: hs.generalFeatures.GeneralFeatures
api-version: '1.21'
load: STARTUP
authors: [ ___Pumpkinn ]

commands:
  grace:
    description: Toggle PvP on or off
    usage: /grace <on|off>
    permission: generalfeatures.grace
    permission-message: You don't have permission to use this command
  restrictions:
    description: Enable or disable various restrictions
    usage: /restrictions <enable|disable> <potions|fireworks|pearls|all> OR /restrictions potions <enable|disable>
    permission: generalfeatures.restrictions
    permission-message: You don't have permission to use this command
  end:
    description: Enable or disable access to the End dimension
    usage: /end <enable|disable>
    permission: generalfeatures.endcontrol
    permission-message: You don't have permission to use this command
  teleportend:
    description: Teleport to the End dimension
    usage: /teleportend
    permission: generalfeatures.teleportend
    permission-message: You don't have permission to use this command
  broadcast:
    description: Send customizable broadcasts to all players
    usage: /broadcast [options] <message>
    permission: generalfeatures.broadcast
    permission-message: You don't have permission to use this command


permissions:
  generalfeatures.grace:
    description: Allows toggling PvP grace period
    default: op
  generalfeatures.restrictions:
    description: Allows managing game restrictions
    default: op
  generalfeatures.endcontrol:
    description: Allows controlling access to the End dimension
    default: op
  generalfeatures.endcontrol.notify:
    description: Receive notifications about End dimension status changes
    default: op
  generalfeatures.teleportend:
    description: Allows teleporting to the End dimension
    default: op
  generalfeatures.broadcast:
    description: Allows sending broadcasts
    default: op