name: GeneralFeatures
version: '1.0-SNAPSHOT'
main: hs.generalFeatures.GeneralFeatures
api-version: '1.21'
load: STARTUP
authors: [ ___Pumpkinn ]

commands:
  grace:
    description: Toggle PvP on or off
    usage: /grace <on|off>
    permission: generalfeatures.grace
    permission-message: You don't have permission to use this command
  restrictions:
    description: Enable or disable various restrictions
    usage: /restrictions <enable|disable> <potions|fireworks|pearls|all>
    permission: generalfeatures.restrictions
    permission-message: You don't have permission to use this command

permissions:
  generalfeatures.grace:
    description: Allows toggling PvP grace period
    default: op
  generalfeatures.restrictions:
    description: Allows managing game restrictions
    default: op